FROM python:alpine
MAINTAINER Kyubi Systems 2020

LABEL version="1.0" maintainer="Kyubi Systems <admin@kyubi.co.uk>"

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN apk add --no-cache --virtual freetype-dev jpeg-dev libpng-dev
RUN apk add --no-cache --virtual cython
RUN pip install --no-cache-dir -r requirements.txt
RUN apk del .build-deps gcc musl-dev

COPY . .

EXPOSE 5000

CMD [ "./start.sh" ]

